### ISSUE TITLE
Add helper function for getting default branch name

### ISSUE THREAD

**Issue by Edholm** [einride/sage#83]
I.e. do this `git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'`

This is useful for building the interval used by our commit linter for example.

**Comment by odsod** [comment]
@Edholm Great idea! Sounds like it would fit under the `mggit` package

**Comment by odsod** [comment]
@Edholm How about this? https://github.com/einride/mage-tools/pull/105

**Comment by Edholm** [comment]
> @Edholm How about this? #105

Perfect!

**Comment by Edholm** [comment]
Closing this for now. Se above PR for more info. Reopen if it becomes relevant in the future.
